name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    runs-on: ubuntu-latest

    env:
      DISABLE_BOOTSNAP: true
      DISABLE_BOOTSNAP_LOAD_PATH_CACHE: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linters
        run: bundle exec rubocop --parallel
      - name: Ruby security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2

  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DISABLE_BOOTSNAP: true
      DISABLE_BOOTSNAP_LOAD_PATH_CACHE: true

    services:
      mysql:
          image: mysql
          env:
            MYSQL_ROOT_PASSWORD: change_me_right_now
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_HOST: 127.0.0.1
          ports:
            - 33306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:     
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Create database
        run: |
          sudo /etc/init.d/mysql start  --skip-grant-tables 
          mysql --host 127.0.0.1 --port 3306 -pchange_me_right_now -uroot -e "SHOW DATABASES"
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests
        run: bundle exec rake
